// Generated by gencpp from file paczka/MoveLin_QResponse.msg
// DO NOT EDIT!


#ifndef PACZKA_MESSAGE_MOVELIN_QRESPONSE_H
#define PACZKA_MESSAGE_MOVELIN_QRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace paczka
{
template <class ContainerAllocator>
struct MoveLin_QResponse_
{
  typedef MoveLin_QResponse_<ContainerAllocator> Type;

  MoveLin_QResponse_()
    {
    }
  MoveLin_QResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::paczka::MoveLin_QResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::paczka::MoveLin_QResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveLin_QResponse_

typedef ::paczka::MoveLin_QResponse_<std::allocator<void> > MoveLin_QResponse;

typedef boost::shared_ptr< ::paczka::MoveLin_QResponse > MoveLin_QResponsePtr;
typedef boost::shared_ptr< ::paczka::MoveLin_QResponse const> MoveLin_QResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::paczka::MoveLin_QResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::paczka::MoveLin_QResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace paczka

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::paczka::MoveLin_QResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::paczka::MoveLin_QResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::paczka::MoveLin_QResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::paczka::MoveLin_QResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::paczka::MoveLin_QResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::paczka::MoveLin_QResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::paczka::MoveLin_QResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::paczka::MoveLin_QResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::paczka::MoveLin_QResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "paczka/MoveLin_QResponse";
  }

  static const char* value(const ::paczka::MoveLin_QResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::paczka::MoveLin_QResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::paczka::MoveLin_QResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::paczka::MoveLin_QResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveLin_QResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::paczka::MoveLin_QResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::paczka::MoveLin_QResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PACZKA_MESSAGE_MOVELIN_QRESPONSE_H
