// Generated by gencpp from file paczka/MoveLin_Q.msg
// DO NOT EDIT!


#ifndef PACZKA_MESSAGE_MOVELIN_Q_H
#define PACZKA_MESSAGE_MOVELIN_Q_H

#include <ros/service_traits.h>


#include <paczka/MoveLin_QRequest.h>
#include <paczka/MoveLin_QResponse.h>


namespace paczka
{

struct MoveLin_Q
{

typedef MoveLin_QRequest Request;
typedef MoveLin_QResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveLin_Q
} // namespace paczka


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::paczka::MoveLin_Q > {
  static const char* value()
  {
    return "2c86974d06038f368935285057a53691";
  }

  static const char* value(const ::paczka::MoveLin_Q&) { return value(); }
};

template<>
struct DataType< ::paczka::MoveLin_Q > {
  static const char* value()
  {
    return "paczka/MoveLin_Q";
  }

  static const char* value(const ::paczka::MoveLin_Q&) { return value(); }
};


// service_traits::MD5Sum< ::paczka::MoveLin_QRequest> should match
// service_traits::MD5Sum< ::paczka::MoveLin_Q >
template<>
struct MD5Sum< ::paczka::MoveLin_QRequest>
{
  static const char* value()
  {
    return MD5Sum< ::paczka::MoveLin_Q >::value();
  }
  static const char* value(const ::paczka::MoveLin_QRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::paczka::MoveLin_QRequest> should match
// service_traits::DataType< ::paczka::MoveLin_Q >
template<>
struct DataType< ::paczka::MoveLin_QRequest>
{
  static const char* value()
  {
    return DataType< ::paczka::MoveLin_Q >::value();
  }
  static const char* value(const ::paczka::MoveLin_QRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::paczka::MoveLin_QResponse> should match
// service_traits::MD5Sum< ::paczka::MoveLin_Q >
template<>
struct MD5Sum< ::paczka::MoveLin_QResponse>
{
  static const char* value()
  {
    return MD5Sum< ::paczka::MoveLin_Q >::value();
  }
  static const char* value(const ::paczka::MoveLin_QResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::paczka::MoveLin_QResponse> should match
// service_traits::DataType< ::paczka::MoveLin_Q >
template<>
struct DataType< ::paczka::MoveLin_QResponse>
{
  static const char* value()
  {
    return DataType< ::paczka::MoveLin_Q >::value();
  }
  static const char* value(const ::paczka::MoveLin_QResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PACZKA_MESSAGE_MOVELIN_Q_H
