// Generated by gencpp from file paczka/MovePTP_Q.msg
// DO NOT EDIT!


#ifndef PACZKA_MESSAGE_MOVEPTP_Q_H
#define PACZKA_MESSAGE_MOVEPTP_Q_H

#include <ros/service_traits.h>


#include <paczka/MovePTP_QRequest.h>
#include <paczka/MovePTP_QResponse.h>


namespace paczka
{

struct MovePTP_Q
{

typedef MovePTP_QRequest Request;
typedef MovePTP_QResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MovePTP_Q
} // namespace paczka


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::paczka::MovePTP_Q > {
  static const char* value()
  {
    return "2c86974d06038f368935285057a53691";
  }

  static const char* value(const ::paczka::MovePTP_Q&) { return value(); }
};

template<>
struct DataType< ::paczka::MovePTP_Q > {
  static const char* value()
  {
    return "paczka/MovePTP_Q";
  }

  static const char* value(const ::paczka::MovePTP_Q&) { return value(); }
};


// service_traits::MD5Sum< ::paczka::MovePTP_QRequest> should match
// service_traits::MD5Sum< ::paczka::MovePTP_Q >
template<>
struct MD5Sum< ::paczka::MovePTP_QRequest>
{
  static const char* value()
  {
    return MD5Sum< ::paczka::MovePTP_Q >::value();
  }
  static const char* value(const ::paczka::MovePTP_QRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::paczka::MovePTP_QRequest> should match
// service_traits::DataType< ::paczka::MovePTP_Q >
template<>
struct DataType< ::paczka::MovePTP_QRequest>
{
  static const char* value()
  {
    return DataType< ::paczka::MovePTP_Q >::value();
  }
  static const char* value(const ::paczka::MovePTP_QRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::paczka::MovePTP_QResponse> should match
// service_traits::MD5Sum< ::paczka::MovePTP_Q >
template<>
struct MD5Sum< ::paczka::MovePTP_QResponse>
{
  static const char* value()
  {
    return MD5Sum< ::paczka::MovePTP_Q >::value();
  }
  static const char* value(const ::paczka::MovePTP_QResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::paczka::MovePTP_QResponse> should match
// service_traits::DataType< ::paczka::MovePTP_Q >
template<>
struct DataType< ::paczka::MovePTP_QResponse>
{
  static const char* value()
  {
    return DataType< ::paczka::MovePTP_Q >::value();
  }
  static const char* value(const ::paczka::MovePTP_QResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PACZKA_MESSAGE_MOVEPTP_Q_H
