// Generated by gencpp from file paczka/MoveLin_P.msg
// DO NOT EDIT!


#ifndef PACZKA_MESSAGE_MOVELIN_P_H
#define PACZKA_MESSAGE_MOVELIN_P_H

#include <ros/service_traits.h>


#include <paczka/MoveLin_PRequest.h>
#include <paczka/MoveLin_PResponse.h>


namespace paczka
{

struct MoveLin_P
{

typedef MoveLin_PRequest Request;
typedef MoveLin_PResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveLin_P
} // namespace paczka


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::paczka::MoveLin_P > {
  static const char* value()
  {
    return "2c86974d06038f368935285057a53691";
  }

  static const char* value(const ::paczka::MoveLin_P&) { return value(); }
};

template<>
struct DataType< ::paczka::MoveLin_P > {
  static const char* value()
  {
    return "paczka/MoveLin_P";
  }

  static const char* value(const ::paczka::MoveLin_P&) { return value(); }
};


// service_traits::MD5Sum< ::paczka::MoveLin_PRequest> should match
// service_traits::MD5Sum< ::paczka::MoveLin_P >
template<>
struct MD5Sum< ::paczka::MoveLin_PRequest>
{
  static const char* value()
  {
    return MD5Sum< ::paczka::MoveLin_P >::value();
  }
  static const char* value(const ::paczka::MoveLin_PRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::paczka::MoveLin_PRequest> should match
// service_traits::DataType< ::paczka::MoveLin_P >
template<>
struct DataType< ::paczka::MoveLin_PRequest>
{
  static const char* value()
  {
    return DataType< ::paczka::MoveLin_P >::value();
  }
  static const char* value(const ::paczka::MoveLin_PRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::paczka::MoveLin_PResponse> should match
// service_traits::MD5Sum< ::paczka::MoveLin_P >
template<>
struct MD5Sum< ::paczka::MoveLin_PResponse>
{
  static const char* value()
  {
    return MD5Sum< ::paczka::MoveLin_P >::value();
  }
  static const char* value(const ::paczka::MoveLin_PResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::paczka::MoveLin_PResponse> should match
// service_traits::DataType< ::paczka::MoveLin_P >
template<>
struct DataType< ::paczka::MoveLin_PResponse>
{
  static const char* value()
  {
    return DataType< ::paczka::MoveLin_P >::value();
  }
  static const char* value(const ::paczka::MoveLin_PResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PACZKA_MESSAGE_MOVELIN_P_H
