// Generated by gencpp from file paczka/pose.msg
// DO NOT EDIT!


#ifndef PACZKA_MESSAGE_POSE_H
#define PACZKA_MESSAGE_POSE_H

#include <ros/service_traits.h>


#include <paczka/poseRequest.h>
#include <paczka/poseResponse.h>


namespace paczka
{

struct pose
{

typedef poseRequest Request;
typedef poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pose
} // namespace paczka


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::paczka::pose > {
  static const char* value()
  {
    return "df30f7cddaf0839095c2022c165dd409";
  }

  static const char* value(const ::paczka::pose&) { return value(); }
};

template<>
struct DataType< ::paczka::pose > {
  static const char* value()
  {
    return "paczka/pose";
  }

  static const char* value(const ::paczka::pose&) { return value(); }
};


// service_traits::MD5Sum< ::paczka::poseRequest> should match
// service_traits::MD5Sum< ::paczka::pose >
template<>
struct MD5Sum< ::paczka::poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::paczka::pose >::value();
  }
  static const char* value(const ::paczka::poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::paczka::poseRequest> should match
// service_traits::DataType< ::paczka::pose >
template<>
struct DataType< ::paczka::poseRequest>
{
  static const char* value()
  {
    return DataType< ::paczka::pose >::value();
  }
  static const char* value(const ::paczka::poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::paczka::poseResponse> should match
// service_traits::MD5Sum< ::paczka::pose >
template<>
struct MD5Sum< ::paczka::poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::paczka::pose >::value();
  }
  static const char* value(const ::paczka::poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::paczka::poseResponse> should match
// service_traits::DataType< ::paczka::pose >
template<>
struct DataType< ::paczka::poseResponse>
{
  static const char* value()
  {
    return DataType< ::paczka::pose >::value();
  }
  static const char* value(const ::paczka::poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PACZKA_MESSAGE_POSE_H
