// Generated by gencpp from file paczka/poseResponse.msg
// DO NOT EDIT!


#ifndef PACZKA_MESSAGE_POSERESPONSE_H
#define PACZKA_MESSAGE_POSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace paczka
{
template <class ContainerAllocator>
struct poseResponse_
{
  typedef poseResponse_<ContainerAllocator> Type;

  poseResponse_()
    {
    }
  poseResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::paczka::poseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::paczka::poseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct poseResponse_

typedef ::paczka::poseResponse_<std::allocator<void> > poseResponse;

typedef boost::shared_ptr< ::paczka::poseResponse > poseResponsePtr;
typedef boost::shared_ptr< ::paczka::poseResponse const> poseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::paczka::poseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::paczka::poseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace paczka

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::paczka::poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::paczka::poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::paczka::poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::paczka::poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::paczka::poseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::paczka::poseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::paczka::poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::paczka::poseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::paczka::poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "paczka/poseResponse";
  }

  static const char* value(const ::paczka::poseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::paczka::poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::paczka::poseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::paczka::poseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct poseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::paczka::poseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::paczka::poseResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PACZKA_MESSAGE_POSERESPONSE_H
