// Generated by gencpp from file paczka/poseRequest.msg
// DO NOT EDIT!


#ifndef PACZKA_MESSAGE_POSEREQUEST_H
#define PACZKA_MESSAGE_POSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace paczka
{
template <class ContainerAllocator>
struct poseRequest_
{
  typedef poseRequest_<ContainerAllocator> Type;

  poseRequest_()
    : tryb()
    , q()  {
    }
  poseRequest_(const ContainerAllocator& _alloc)
    : tryb(_alloc)
    , q(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _tryb_type;
  _tryb_type tryb;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _q_type;
  _q_type q;





  typedef boost::shared_ptr< ::paczka::poseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::paczka::poseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct poseRequest_

typedef ::paczka::poseRequest_<std::allocator<void> > poseRequest;

typedef boost::shared_ptr< ::paczka::poseRequest > poseRequestPtr;
typedef boost::shared_ptr< ::paczka::poseRequest const> poseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::paczka::poseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::paczka::poseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::paczka::poseRequest_<ContainerAllocator1> & lhs, const ::paczka::poseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.tryb == rhs.tryb &&
    lhs.q == rhs.q;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::paczka::poseRequest_<ContainerAllocator1> & lhs, const ::paczka::poseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace paczka

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::paczka::poseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::paczka::poseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::paczka::poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::paczka::poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::paczka::poseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::paczka::poseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::paczka::poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df30f7cddaf0839095c2022c165dd409";
  }

  static const char* value(const ::paczka::poseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf30f7cddaf08390ULL;
  static const uint64_t static_value2 = 0x95c2022c165dd409ULL;
};

template<class ContainerAllocator>
struct DataType< ::paczka::poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "paczka/poseRequest";
  }

  static const char* value(const ::paczka::poseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::paczka::poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string tryb\n"
"float32[] q\n"
;
  }

  static const char* value(const ::paczka::poseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::paczka::poseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tryb);
      stream.next(m.q);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct poseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::paczka::poseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::paczka::poseRequest_<ContainerAllocator>& v)
  {
    s << indent << "tryb: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.tryb);
    s << indent << "q[]" << std::endl;
    for (size_t i = 0; i < v.q.size(); ++i)
    {
      s << indent << "  q[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.q[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACZKA_MESSAGE_POSEREQUEST_H
