// Generated by gencpp from file paczka/Stop.msg
// DO NOT EDIT!


#ifndef PACZKA_MESSAGE_STOP_H
#define PACZKA_MESSAGE_STOP_H

#include <ros/service_traits.h>


#include <paczka/StopRequest.h>
#include <paczka/StopResponse.h>


namespace paczka
{

struct Stop
{

typedef StopRequest Request;
typedef StopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Stop
} // namespace paczka


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::paczka::Stop > {
  static const char* value()
  {
    return "3a9a8ccf1ae2be3477477819c0d93b4e";
  }

  static const char* value(const ::paczka::Stop&) { return value(); }
};

template<>
struct DataType< ::paczka::Stop > {
  static const char* value()
  {
    return "paczka/Stop";
  }

  static const char* value(const ::paczka::Stop&) { return value(); }
};


// service_traits::MD5Sum< ::paczka::StopRequest> should match
// service_traits::MD5Sum< ::paczka::Stop >
template<>
struct MD5Sum< ::paczka::StopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::paczka::Stop >::value();
  }
  static const char* value(const ::paczka::StopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::paczka::StopRequest> should match
// service_traits::DataType< ::paczka::Stop >
template<>
struct DataType< ::paczka::StopRequest>
{
  static const char* value()
  {
    return DataType< ::paczka::Stop >::value();
  }
  static const char* value(const ::paczka::StopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::paczka::StopResponse> should match
// service_traits::MD5Sum< ::paczka::Stop >
template<>
struct MD5Sum< ::paczka::StopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::paczka::Stop >::value();
  }
  static const char* value(const ::paczka::StopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::paczka::StopResponse> should match
// service_traits::DataType< ::paczka::Stop >
template<>
struct DataType< ::paczka::StopResponse>
{
  static const char* value()
  {
    return DataType< ::paczka::Stop >::value();
  }
  static const char* value(const ::paczka::StopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PACZKA_MESSAGE_STOP_H
